### PR TITLE
Add option to increase/decrease volume level by given [VALUE]

### PR DESCRIPTION
**Pull request by KeyofBlueS**
Hi, this PR add option to increase/decrease volume level by given [VALUE] (along with code cleanup).

Best regards.

### CODE REVIEW

**Comment by swarminglogic** [comment]
Thanks for the PR. If you wouldn't mind using the same indentation style (i.e. spaces), I'd be much happier to review/merge it. It would make it easier to see what has changed.

**Comment by KeyofBlueS** [comment]
Here it is :+1:

**Review by swarminglogic — APPROVED** [review]
LGTM

**Comment by swarminglogic** [comment]
Thanks @KeyofBlueS :)

**Pull request merged**
